import { useSetAtom } from 'jotai'
import Head from 'next/head'
import { useEffect } from 'react'

import { QuestionLayout } from '@/component/layout/QuestionLayout'
import { isActiveTabAtom, isMainActiveTabAtom } from '@/store/atom'

import { QuestionWaitingAnswers } from './QuestionWaitingAnswers'

/**
 * @package
 */

export const QuestionWaitingAnswersPage = () => {
  const setActiveTab = useSetAtom(isActiveTabAtom)
  const setIsMainActiveTab = useSetAtom(isMainActiveTabAtom)

  useEffect(() => {
    setIsMainActiveTab('questions')
    setActiveTab('question-waiting-answers')
  }, [setActiveTab, setIsMainActiveTab])

  return (
    <>
      <Head>
        <title>Recurrot - 回答募集中</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <QuestionLayout>
        <QuestionWaitingAnswers />
      </QuestionLayout>
    </>
  )
}
