import Head from 'next/head'

import { useNavTab } from '@/common/hook/useNavTab'
import { QuestionLayout } from '@/component/layout/QuestionLayout'

import { QuestionWaitingAnswers } from './QuestionWaitingAnswers'

/**
 * @package
 */

export const QuestionWaitingAnswersPage = () => {
  useNavTab('questions', 'question-waiting-answers')

  return (
    <>
      <Head>
        <title>Recurrot - 回答募集中</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <QuestionLayout>
        <QuestionWaitingAnswers />
      </QuestionLayout>
    </>
  )
}
