import Head from 'next/head'

import { useNavTab } from '@/common/hook/useNavTab'
import { useQueryQuestionListAnswered } from '@/common/hook/useQueryQuestionListAnswered'
import { QuestionLayout } from '@/component/layout/QuestionLayout'
import { QuestionLoading } from '@/component/ui/Loading'

import { QuestionsAnswered } from './QuestionsAnswered'

/**
 * @package
 */

export const QuestionsAnsweredPage = () => {
  const { data: questionList, status: questionListStatus } = useQueryQuestionListAnswered()

  useNavTab('questions', 'questions-answered')

  if (questionListStatus === 'loading') return <QuestionLoading />

  return (
    <>
      <Head>
        <title>Recurrot - 回答した質問</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <QuestionLayout>{questionList && <QuestionsAnswered questionList={questionList} />}</QuestionLayout>
    </>
  )
}
