import Head from 'next/head'
import { useEffect } from 'react'

import { useQueryUser } from '@/common/hook/useQueryUser'
import { useSubNavTabStyle } from '@/component/layout/Navigation/useSubNavTabStyle'
import { Loading } from '@/component/ui/Loading'
import { ProfileCard } from '@/component/ui/ProfileCard'

const MyProfile = () => {
  const { data: user, status: UserStatus } = useQueryUser()

  const { handleSubNavTabStyle } = useSubNavTabStyle()

  useEffect(() => {
    handleSubNavTabStyle('dashboard/my-profile')
  })

  if (UserStatus === 'loading') return <Loading />

  return (
    <>
      <Head>
        <title>Recurrot - プロフィール</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className=' flex h-fit flex-1 justify-center'>
        <div className=' flex w-full max-w-[1200px] justify-center px-8 '>
          <div className=' h-fit w-full py-5 sm:w-9/12 '>{user && <ProfileCard user={user} />}</div>
        </div>
      </main>
    </>
  )
}

export const getServerSideProps = async () => {
  return {
    props: {
      layout: 'WrapperLayout',
    },
  }
}

export default MyProfile
