import { useSetAtom } from 'jotai'
import Head from 'next/head'
import { useEffect } from 'react'

import { useQueryUser } from '@/common/hook/useQueryUser'
import { ProfileLoading } from '@/component/ui/Loading'
import { ProfileCard } from '@/component/ui/ProfileCard'
import { navTabAtom } from '@/store/question-atom'

const MyProfile = () => {
  const { data: user, status: UserStatus } = useQueryUser()

  const setNavTab = useSetAtom(navTabAtom)

  useEffect(() => {
    setNavTab({ main: 'questions', sub: 'my-profile' })
  }, [setNavTab])

  if (UserStatus === 'loading') return <ProfileLoading />

  return (
    <>
      <Head>
        <title>Recurrot - プロフィール</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className=' flex h-fit flex-1 justify-center'>
        <div className=' flex w-full max-w-[1200px] justify-center px-8 '>
          <div className=' flex h-fit w-full items-center justify-center py-5 '>
            {user && <ProfileCard user={user} />}
          </div>
        </div>
      </main>
    </>
  )
}

export const getServerSideProps = async () => {
  return {
    props: {
      layout: 'WrapperLayout',
    },
  }
}

export default MyProfile
