import Head from 'next/head'
import { useEffect } from 'react'

import { WrapperLayout } from '@/component/layout/WrapperLayout'
import { useSubNavTabStyle } from '@/component/ui/Navigation/useSubNavTabStyle'
import { ProfileCard } from '@/component/ui/ProfileCard'

const MyProfile = () => {
  const { handleSubNavTabStyle } = useSubNavTabStyle()

  useEffect(() => {
    handleSubNavTabStyle('dashboard/my-profile')
  })
  return (
    <>
      <Head>
        <title>Recurrot - プロフィール</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <WrapperLayout>
        <main className=' flex h-fit flex-1 justify-center'>
          <div className=' w-9/12 py-5'>
            <ProfileCard />
          </div>
        </main>
      </WrapperLayout>
    </>
  )
}
export default MyProfile
