import { useSetAtom } from 'jotai'
import Head from 'next/head'
import { useEffect } from 'react'

import { useQueryMyQuestionList } from '@/common/hook/useQueryMyQuestionList'
import type { MyQuestion } from '@/common/type'
import { QuestionLayout } from '@/component/layout/QuestionLayout'
import { Card } from '@/component/ui/Card'
import { QuestionLoading } from '@/component/ui/Loading'
import { navTabAtom } from '@/store/question-atom'

const MyQuestions = () => {
  const { data: myQuestionList, status: myQuestionListStatus } = useQueryMyQuestionList()

  const setNavTab = useSetAtom(navTabAtom)

  useEffect(() => {
    setNavTab({ main: 'questions', sub: 'my-questions' })
  }, [setNavTab])

  if (myQuestionListStatus === 'loading') return <QuestionLoading />

  return (
    <>
      <Head>
        <title>Recurrot - 自分の質問</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <QuestionLayout>
        {myQuestionList &&
          myQuestionList.map((question: MyQuestion) => {
            return <Card key={question.id} question={question} />
          })}
      </QuestionLayout>
    </>
  )
}

export const getServerSideProps = async () => {
  return {
    props: {
      layout: 'WrapperLayout',
    },
  }
}

export default MyQuestions
