import { useQuery } from '@tanstack/react-query'
import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import router from 'next/router'

import type { QuestionAndAnswerIdListType } from '@/common/type'
import { QuestionLayout } from '@/component/layout/QuestionLayout'
import { Card } from '@/component/ui/Card'

type NewQuestionsProps = {
  initialData: QuestionAndAnswerIdListType[]
}

const NewQuestions: NextPage<NewQuestionsProps> = ({ initialData }) => {
  const { data: questions } = useQuery<QuestionAndAnswerIdListType[], Error>({
    queryKey: ['questions'],
    queryFn: getQuestions,
    initialData,
    staleTime: 10000, //5分
    onError: (err: any) => {
      if (err.response.status === 401 || err.response.status === 403) router.push('/')
    },
  })

  return (
    <>
      <Head>
        <title>Recurrot - 新着</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <QuestionLayout>
        {questions.map((question: QuestionAndAnswerIdListType, index) => {
          return <Card key={index} question={question} />
        })}
      </QuestionLayout>
    </>
  )
}

const getQuestions = async () => {
  const { data } = await axios.get<QuestionAndAnswerIdListType[]>(`${process.env.NEXT_PUBLIC_API_URL}/question`)
  return data
}

export const getServerSideProps = async () => {
  const initialData = await getQuestions()
  return {
    props: {
      layout: 'WrapperLayout',
      initialData,
    },
  }
}

export default NewQuestions
