import { useSetAtom } from 'jotai'
import Head from 'next/head'
import { useEffect } from 'react'

import { useQueryQuestions } from '@/common/hook/useQueryQuestions'
import type { QuestionAndAnswerIdListType } from '@/common/type'
import { QuestionLayout } from '@/component/layout/QuestionLayout'
import { Card } from '@/component/ui/Card'
import { QuestionLoading } from '@/component/ui/Loading'
import { isLoadingAtom, navTabAtom } from '@/store/question-atom'

const NewQuestions = () => {
  const { data: questions, status: questionsStatus } = useQueryQuestions()
  const setIsLoading = useSetAtom(isLoadingAtom)

  const setNavTab = useSetAtom(navTabAtom)

  useEffect(() => {
    setIsLoading(false)
  }, [setIsLoading])

  useEffect(() => {
    setNavTab({ main: 'questions', sub: 'new-questions' })
  }, [setNavTab])

  if (questionsStatus === 'loading') return <QuestionLoading />

  return (
    <>
      <Head>
        <title>Recurrot - 新着</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <QuestionLayout>
        {questions &&
          questions.map((question: QuestionAndAnswerIdListType, index) => {
            return <Card key={index} question={question} />
          })}
      </QuestionLayout>
    </>
  )
}

export const getServerSideProps = async () => {
  return {
    props: {
      layout: 'WrapperLayout',
    },
  }
}

export default NewQuestions
