import Head from 'next/head'

import { ProfileCard } from '@/component/ui/ProfileCard'

const profile = () => {
  return (
    <>
      <Head>
        <title>userName - Recurrot</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className=' flex h-full justify-center'>
        <div className=' w-9/12 py-5'>
          <ProfileCard />
        </div>
      </main>
    </>
  )
}
export default profile
