import Head from 'next/head'
import { useLayoutEffect } from 'react'

import { useMainNavTabStyle } from '@/component/ui/Navigation/useMainNavTabStyle'
import { useSubNavTabStyle } from '@/component/ui/Navigation/useSubNavTabStyle'
import { ProfileCard } from '@/component/ui/ProfileCard'

const Profile = () => {
  const { handleNavTabStyle } = useMainNavTabStyle()
  const { handleSubNavTabStyle } = useSubNavTabStyle()

  useLayoutEffect(() => {
    handleNavTabStyle('dashboard')
    handleSubNavTabStyle('dashboard-profile')
  })
  return (
    <>
      <Head>
        <title>userName - Recurrot</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className=' flex h-full justify-center'>
        <div className=' w-9/12 py-5'>
          <ProfileCard />
        </div>
      </main>
    </>
  )
}
export default Profile
