import { useSetAtom } from 'jotai'
import Head from 'next/head'
import { useEffect } from 'react'

// import { Card } from '@/component/ui/Card'
import { QuestionLayout } from '@/component/layout/QuestionLayout'
import { navTabAtom } from '@/store/question-atom'

const QuestionWaitingAnswers = () => {
  const setNavTab = useSetAtom(navTabAtom)

  useEffect(() => {
    setNavTab({ main: 'questions', sub: 'question-waiting-answers' })
  }, [setNavTab])

  return (
    <>
      <Head>
        <title>Recurrot - 回答募集中</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <QuestionLayout>{/* <Card /> */}</QuestionLayout>
    </>
  )
}

export const getServerSideProps = async () => {
  return {
    props: {
      layout: 'WrapperLayout',
    },
  }
}

export default QuestionWaitingAnswers
