import Head from 'next/head'
import { useEffect } from 'react'

// import { Card } from '@/component/ui/Card'
import { useSubNavTabStyle } from '@/component/layout/Navigation/useSubNavTabStyle'

const QuestionWaitingAnswers = () => {
  const { handleSubNavTabStyle } = useSubNavTabStyle()

  useEffect(() => {
    handleSubNavTabStyle('dashboard/question-waiting-answers')
  })

  return (
    <>
      <Head>
        <title>Recurrot - 回答募集中</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className=' flex h-fit flex-1 justify-center'>
        <div className=' grid w-9/12 grid-cols-3 gap-10 py-5'>{/* <Card /> */}</div>
      </main>
    </>
  )
}

export const getServerSideProps = async () => {
  return {
    props: {
      layout: 'WrapperLayout',
    },
  }
}

export default QuestionWaitingAnswers
