import { useSetAtom } from 'jotai'
import Head from 'next/head'
import { useEffect } from 'react'

import { useQueryMyAnsweredQuestionList } from '@/common/hook/useQueryMyAnsweredQuestionList'
import { QuestionLayout } from '@/component/layout/QuestionLayout'
import { QuestionLoading } from '@/component/ui/Loading'
import { navTabAtom } from '@/store/atom'

import { MyAnswers } from './MyAnswers'

/**
 * @package
 */

export const MyAnswersPage = () => {
  const { data: questions, status: answersStatus } = useQueryMyAnsweredQuestionList()

  const setNavTab = useSetAtom(navTabAtom)

  useEffect(() => {
    setNavTab({ main: 'questions', sub: 'my-answers' })
  }, [setNavTab])

  if (answersStatus === 'loading') return <QuestionLoading />

  return (
    <>
      <Head>
        <title>Recurrot - 自分の回答</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <QuestionLayout>{questions && <MyAnswers questions={questions} />}</QuestionLayout>
    </>
  )
}
