import Head from 'next/head'

import { QuestionForm } from '@/component/ui/Form/Question'

const QuestionEdit = () => {
  return (
    <>
      <Head>
        <title>Recurrot - 新着</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className=' flex flex-1 justify-center p-5'>
        <QuestionForm />
      </main>
    </>
  )
}

export const getServerSideProps = async () => {
  return {
    props: {
      layout: 'WrapperLayout',
    },
  }
}

export default QuestionEdit
