import { useSetAtom } from 'jotai'
import Head from 'next/head'
import { useRouter } from 'next/router'

import { useNavTab } from '@/common/hook/useNavTab'
import { useQueryCurrentUser } from '@/common/hook/useQueryCurrentUser'
import { useQuerySingleQuestion } from '@/common/hook/useQuerySingleQuestion'
import { useRouterEvent } from '@/common/hook/useRouterEvent'
import { QuestionLoading } from '@/component/ui/Loading'
import NotFoundPage from '@/pages/404'
import { resetEditedQuestionAtom, resetQuestionDescriptionAtom } from '@/store/atom'

import { QuestionDetail } from './QuestionDetail'

/**
 * @package
 */

export const QuestionDetailPage = () => {
  const resetEditedQuestion = useSetAtom(resetEditedQuestionAtom)
  const resetDescription = useSetAtom(resetQuestionDescriptionAtom)

  useNavTab('null', 'null')
  useRouterEvent({ eventName: 'routeChangeComplete', callback: resetEditedQuestion })
  useRouterEvent({ eventName: 'routeChangeComplete', callback: resetDescription })
  const router = useRouter()
  const { data: question, isLoading, isError } = useQuerySingleQuestion(router.query.id)
  const { data: currentUser, status: currentUserStatus } = useQueryCurrentUser()

  if (isError) return <NotFoundPage />

  if (isLoading || currentUserStatus === 'loading') return <QuestionLoading />

  return (
    <>
      {question && currentUser && (
        <>
          <Head>
            <title>Recurrot - {question.title} </title>
            <meta name='description' content='Generated by create next app' />
            <meta name='viewport' content='width=device-width, initial-scale=1' />
            <link rel='icon' href='/favicon.ico' />
          </Head>

          <QuestionDetail id={question.id} question={question} currentUser={currentUser} />
        </>
      )}
    </>
  )
}
