import { useSetAtom } from 'jotai'
import Head from 'next/head'
import { useEffect } from 'react'

import { ProfileLoading } from '@/component/ui/Loading'
import { isActiveTabAtom } from '@/store/atom'

import { useQueryMyProfile } from './hook'
import { MyProfile } from './MyProfile'

export const MyProfilePage = () => {
  const { data: myProfile, status: UserStatus } = useQueryMyProfile()

  const setActiveTab = useSetAtom(isActiveTabAtom)

  useEffect(() => {
    setActiveTab('my-profile')
  }, [setActiveTab])

  if (UserStatus === 'loading') return <ProfileLoading />

  return (
    <>
      <Head>
        <title>Recurrot - プロフィール</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {myProfile && <MyProfile myProfile={myProfile} />}
    </>
  )
}
