import Head from 'next/head'

import { WrapperLayout } from '@/component/layout/WrapperLayout'
import { QuestionForm } from '@/component/ui/Form/Question'

const QuestionPost = () => {
  return (
    <>
      <Head>
        <title>Recurrot - 新着</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <WrapperLayout>
        <main className=' flex flex-1 justify-center p-5'>
          <QuestionForm />
        </main>
      </WrapperLayout>
    </>
  )
}
export default QuestionPost
