import { useSetAtom } from 'jotai'
import Head from 'next/head'
import { useEffect } from 'react'

import { useQueryPostedQuestionList } from '@/common/hook/useQueryPostedQuestionList'
import { QuestionLayout } from '@/component/layout/QuestionLayout'
import { QuestionLoading } from '@/component/ui/Loading'
import { isActiveTabAtom } from '@/store/atom'

import { PostedQuestions } from './PostedQuestions'

/**
 * @package
 */

export const PostedQuestionsPage = () => {
  const { data: postedQuestionList, status: postedQuestionListStatus } = useQueryPostedQuestionList()

  const setActiveTab = useSetAtom(isActiveTabAtom)

  useEffect(() => {
    setActiveTab('posted-questions')
  }, [setActiveTab])

  if (postedQuestionListStatus === 'loading') return <QuestionLoading />

  return (
    <>
      <Head>
        <title>Recurrot - 自分の質問</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <QuestionLayout>
        {postedQuestionList && <PostedQuestions postedQuestionList={postedQuestionList} />}
      </QuestionLayout>
    </>
  )
}
