import { useSetAtom } from 'jotai'
import Head from 'next/head'
import { useEffect } from 'react'

import { useQueryMyQuestionList } from '@/common/hook/useQueryMyQuestionList'
import { QuestionLayout } from '@/component/layout/QuestionLayout'
import { QuestionLoading } from '@/component/ui/Loading'
import { navTabAtom } from '@/store/atom'

import { MyQuestions } from './MyQuestions'

/**
 * @package
 */

export const MyQuestionsPage = () => {
  const { data: myQuestionList, status: myQuestionListStatus } = useQueryMyQuestionList()

  const setNavTab = useSetAtom(navTabAtom)

  useEffect(() => {
    setNavTab({ main: 'questions', sub: 'my-questions' })
  }, [setNavTab])

  if (myQuestionListStatus === 'loading') return <QuestionLoading />

  return (
    <>
      <Head>
        <title>Recurrot - 自分の質問</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <QuestionLayout>{myQuestionList && <MyQuestions myQuestionList={myQuestionList} />}</QuestionLayout>
    </>
  )
}
