import { useSetAtom } from 'jotai'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'

import { useQuerySearchQuestions } from '@/common/hook/useQuerySearchQuestions'
import { QuestionLayout } from '@/component/layout/QuestionLayout'
import { QuestionLoading } from '@/component/ui/Loading'
import { isActiveTabAtom } from '@/store/atom'

import { Search } from './Search'

/**
 * @package
 */

export const SearchPage = () => {
  const [id, setId] = useState<string>('')
  const router = useRouter()

  useEffect(() => {
    if (router.isReady) {
      if (typeof router.query.q === 'string') {
        setId(router.query.q)
      }
    }
  }, [router])

  const { data: searchQuestionList, status: searchQuestionListStatus } = useQuerySearchQuestions(id)

  const setActiveTab = useSetAtom(isActiveTabAtom)

  useEffect(() => {
    setActiveTab(null)
  }, [setActiveTab])

  if (searchQuestionListStatus === 'loading') return <QuestionLoading />

  return (
    <>
      <Head>
        <title>Recurrot - 新着</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <QuestionLayout>{searchQuestionList && <Search searchQuestionList={searchQuestionList} />}</QuestionLayout>
    </>
  )
}
