import Head from 'next/head'

import { useNavTab } from '@/common/hook/useNavTab'
import { useQueryNewQuestionList } from '@/common/hook/useQueryNewQuestionList'
import { QuestionLayout } from '@/component/layout/QuestionLayout'
import { QuestionLoading } from '@/component/ui/Loading'

import { NewQuestions } from './NewQuestions'

/**
 * @package
 */

export const NewQuestionsPage = () => {
  const { data: newQuestionList, status: newQuestionListStatus } = useQueryNewQuestionList()

  useNavTab('questions', 'new-questions')

  if (newQuestionListStatus === 'loading') return <QuestionLoading />

  return (
    <>
      <Head>
        <title>Recurrot - 新着</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <QuestionLayout>{newQuestionList && <NewQuestions newQuestionList={newQuestionList} />}</QuestionLayout>
    </>
  )
}
