import { useSetAtom } from 'jotai'
import Head from 'next/head'
import { useEffect } from 'react'

import { useQueryNewQuestionList } from '@/common/hook/useQueryNewQuestionList'
import { QuestionLayout } from '@/component/layout/QuestionLayout'
import { QuestionLoading } from '@/component/ui/Loading'
import { isLoadingAtom, navTabAtom } from '@/store/atom'

import { NewQuestions } from './NewQuestions'

/**
 * @package
 */

export const NewQuestionsPage = () => {
  const { data: newQuestionList, status: newQuestionListStatus } = useQueryNewQuestionList()
  const setIsLoading = useSetAtom(isLoadingAtom)

  const setNavTab = useSetAtom(navTabAtom)

  useEffect(() => {
    setIsLoading(false)
  }, [setIsLoading])

  useEffect(() => {
    setNavTab({ main: 'questions', sub: 'new-questions' })
  }, [setNavTab])

  if (newQuestionListStatus === 'loading') return <QuestionLoading />

  return (
    <>
      <Head>
        <title>Recurrot - 新着</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <QuestionLayout>{newQuestionList && <NewQuestions newQuestionList={newQuestionList} />}</QuestionLayout>
    </>
  )
}
